import { Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Oversized T-Shirt',
    slug: 'oversized-t-shirt',
    description: 'Premium cotton oversized t-shirt for daily comfort.',
    price: 790,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1480&auto=format&fit=crop'],
    stock: 50,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Orange', 'Black', 'White'],
    tags: ['new-arrival', 'trending'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Casual Shirt',
    slug: 'casual-shirt',
    description: 'Comfortable casual shirt for everyday wear.',
    price: 1390,
    images: ['https://images.unsplash.com/photo-1596755094514-f87e32f85e2c?q=80&w=1288&auto=format&fit=crop'],
    stock: 30,
    sizes: ['M', 'L', 'XL'],
    colors: ['Green', 'Navy'],
    tags: ['best-seller', 'premium'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Varsity Jacket',
    slug: 'varsity-jacket',
    description: 'Classic varsity jacket with premium finish.',
    price: 2490,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1335&auto=format&fit=crop'],
    stock: 20,
    sizes: ['M', 'L'],
    colors: ['Yellow', 'Black'],
    tags: ['trending'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Printed Shirt',
    slug: 'printed-shirt',
    description: 'Stylish printed shirt for a bold look.',
    price: 1190,
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1470&auto=format&fit=crop'],
    stock: 40,
    sizes: ['S', 'M', 'L'],
    colors: ['White', 'Blue'],
    tags: ['new-arrival'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Cargo Vest',
    slug: 'cargo-vest',
    description: 'Utility cargo vest with multiple pockets.',
    price: 1890,
    images: ['https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?q=80&w=1287&auto=format&fit=crop'],
    stock: 15,
    sizes: ['M', 'L', 'XL'],
    colors: ['Black', 'Olive'],
    tags: ['premium'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Windbreaker',
    slug: 'windbreaker',
    description: 'Lightweight windbreaker for outdoor activities.',
    price: 1590,
    images: ['https://images.unsplash.com/photo-1548883354-7622d03aca27?q=80&w=1355&auto=format&fit=crop'],
    stock: 25,
    sizes: ['M', 'L', 'XL'],
    colors: ['Green', 'Black'],
    tags: ['discounted'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];
